#!/bin/sh
xx='000'$1
yy='bbb'

#count=0 ; echo $count $xx $yy
while test $yy != 'aaa'
do
 zz=`echo $xx | sed 's/^0//'` 
 if test $zz = $xx
 then
   echo $xx
   exit 1
 else
  xx=$zz
  yy=`echo $xx | sed 's/^...$/aaa/'`
  #count=`expr $count + 1` ; echo $count $xx $yy
  #if test $count = 10 ; then yy='aaa' ; fi
 fi
done
echo $xx
exit 0
