#!/bin/csh
set xx = '0000'$1
set yy = `echo $xx | sed 's/^....$/aaaa/'`

while ( $yy != 'aaaa' )
 set xx = `echo $xx | sed 's/^0//'` 
 set yy = `echo $xx | sed 's/^....$/aaaa/'`
 # echo $xx $yy
end
echo $xx
exit
