#!/bin/csh
set xx = '0000000000'$1
set yy = `echo $xx | sed 's/^..........$/aaaaaaaaaa/'`

while ( $yy != 'aaaaaaaaaa' )
 set xx = `echo $xx | sed 's/^0//'` 
 set yy = `echo $xx | sed 's/^..........$/aaaaaaaaaa/'`
 # echo $xx $yy
end
echo $xx
exit
