#! /bin/sh
case $# in
  2|3|4|5) ;;
    *) echo "Usage: `basename $0` [-s] [Dir] old_prefx new_prefx [prefx_selecteur]"
       echo " -s : silent mode"
       echo "Dir : move directories"
       exit ;;
esac
cmd='ls' ; opt='-f' ;
if test $1 = '-s' ; then verb=0 ; shift ; else verb=1 ; fi
if test $1 = 'Dir' ; then cmd='ls -d' ; opt='-d' ; shift ; fi
rac=$1
new=$2
if test $rac = '=' ; then rac='' ; fi
if test $new = '=' ; then new='' ; fi
if test $# = "3" ; then sel=$3 ; else sel=$rac ; fi
#---+----1----+----2----+----3----+----4----+----5----+----6----+----7-|--+----|
liste=`$cmd ${sel}*`
#echo $liste ; exit
for xx in $liste
do
  sufx=`echo $xx | sed "s/^$sel//g"` 
  #echo $sufx
  if test $opt $rac$sufx 
  then 
       if test $verb = 1 
       then echo mv $rac$sufx $new$sufx ; fi
              mv -i $rac$sufx $new$sufx
  else echo pas de fichier $rac$sufx
  fi
done
exit
